language: node_js

node_js:
- '6'

script: npm test

notifications:
  email: false
<% if (!isYarnAvailable) { %>
cache:
  directories:
    - node_modules
<% } else { %>
cache: yarn
<% } %>
after_success:
- npm run codecov