language: node_js

node_js:
  - '8'
  - '6'
  - '4'

script: npm test

notifications:
  email: false

cache: yarn

addons:
  chrome: stable

dist: trusty

before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm i -g npm@^5.0.0; fi'